{ pkgs, lib,... }:
{
  virtualisation.oci-containers.containers."ct-emby" = {
    image = "emby/embyserver:beta";
    environment = {
      "GID" = "100";
      "GIDLIST" = "44,105";
      "UID" = "1000";
    };
    volumes = [
      "/daten/arr-suite:/daten/arr-suite:rw"
      "vl-emby-config:/config:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri:/dev/dri"
      "--network-alias=ct-emby"
      "--network=nw-emby"
      "--network=nw-proxy"
    ];
  };
  systemd.services."docker-ct-emby" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    partOf = [
      "docker-compose-emby-root.target"
    ];
    wantedBy = [
      "docker-compose-emby-root.target"
    ];
  };
  systemd.targets."docker-compose-emby-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
